name: Daily Stock Data Sync (Backend)

on:
  schedule:
    - cron: '0 14,16,18,20,22 * * 1-5' # Cada 2 horas de 11:00 AM a 7:00 PM AR, de lunes a viernes
  workflow_dispatch: # Permite correrlo manualmente desde la pestaña "Actions"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Extraer código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        working-directory: ./scripts
        run: npm install

      - name: Descargar API y Actualizar Nube
        working-directory: ./scripts
        env:
          API_KEY: ${{ secrets.API_KEY }} 
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: node update-data.js
